# application.yml

# Server configuration
server:
  port: 8080  # Port on which the server will run
  shutdown: GRACEFUL  # Graceful shutdown of the server

# Logging configuration
logging:
  level:
    com.example.microservice.config: INFO  # Log level for custom application configurations
    org.springframework.data.mongodb: DEBUG  # Log level for Spring Data MongoDB
    com.mongodb: DEBUG  # Log level for MongoDB driver

# Include external configurations
spring.config.import:
  - "classpath:health-check.yml"
  - "classpath:management.yml"
  - "classpath:springdoc.yml"
  - "classpath:spring-data.yml"
  - "classpath:info.yml"
