# application.yml

# Server configuration
server:
  port: 8080

# Spring Configuration
spring:
  profiles:
    # Active Spring profile, can be "dev", "prod", "test", etc.
    active: dev

  # External Configurations Import
  config:
    import:
      # External configuration files to be included
      - "classpath:health-check.yml"
      - "classpath:management.yml"
      - "classpath:springdoc.yml"
      - "classpath:spring-data.yml"
      - "classpath:info.yml"

# Logging Configuration
logging:
  file:
    name: build/logs/spring-boot-app.log  # Specify the file path
  level:
    org.springframework.test.context.support.AnnotationConfigContextLoaderUtils: ERROR
