# spring-data.yml

spring:
  application:
    name: microservice  # Application name for identification
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  # Exclude DataSource auto-configuration since MongoDB is used
  data:
    mongodb:
      uri: mongodb://localhost:27017/microservice  # MongoDB connection URI
